/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnaliseDePecasRouteImport } from './routes/analise-de-pecas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ProcessosRouteImport } from './routes/processos'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ProcessosIndexRouteImport } from './routes/processos.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseDePecasRoute = AnaliseDePecasRouteImport.update({
  id: '/analise-de-pecas',
  path: '/analise-de-pecas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosRoute = ProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosIndexRoute = ProcessosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcessosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise-de-pecas': typeof AnaliseDePecasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/processos': typeof ProcessosRouteWithChildren
  '/radar': typeof RadarRoute
  '/processos/': typeof ProcessosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise-de-pecas': typeof AnaliseDePecasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/radar': typeof RadarRoute
  '/processos': typeof ProcessosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise-de-pecas': typeof AnaliseDePecasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/processos': typeof ProcessosRouteWithChildren
  '/radar': typeof RadarRoute
  '/processos/': typeof ProcessosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise-de-pecas'
    | '/configuracoes'
    | '/processos'
    | '/radar'
    | '/processos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analise-de-pecas' | '/configuracoes' | '/radar' | '/processos'
  id:
    | '__root__'
    | '/'
    | '/analise-de-pecas'
    | '/configuracoes'
    | '/processos'
    | '/radar'
    | '/processos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseDePecasRoute: typeof AnaliseDePecasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ProcessosRoute: typeof ProcessosRouteWithChildren
  RadarRoute: typeof RadarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-de-pecas': {
      id: '/analise-de-pecas'
      path: '/analise-de-pecas'
      fullPath: '/analise-de-pecas'
      preLoaderRoute: typeof AnaliseDePecasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos': {
      id: '/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/': {
      id: '/processos/'
      path: '/'
      fullPath: '/processos/'
      preLoaderRoute: typeof ProcessosIndexRouteImport
      parentRoute: typeof ProcessosRoute
    }
  }
}

interface ProcessosRouteChildren {
  ProcessosIndexRoute: typeof ProcessosIndexRoute
}

const ProcessosRouteChildren: ProcessosRouteChildren = {
  ProcessosIndexRoute: ProcessosIndexRoute,
}

const ProcessosRouteWithChildren = ProcessosRoute._addFileChildren(
  ProcessosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseDePecasRoute: AnaliseDePecasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ProcessosRoute: ProcessosRouteWithChildren,
  RadarRoute: RadarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
